name: my_app
description: therapiani
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  auto_route: 9.2.2
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flex_color_scheme: ^8.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_svg: ^2.0.14
  lottie: ^3.1.3
  font_awesome_flutter: ^10.8.0
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  swipeable_page_route: ^0.4.4

dev_dependencies:
  auto_route_generator: 9.0.0
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
  flutter_gen_runner:
  build_runner:

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/
    - assets/vectors/


flutter_intl:
  enabled: true


flutter_gen:
  output: lib/app/services/
  line_length: 80
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true
